services:
  backend:
    build:
      context: ./backend
    environment:
      - GOOGLE_TTS_API_KEY=${GOOGLE_TTS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_HOSTNAME=${API_HOSTNAME}
    ports:
      - "8001:8000"
    volumes:
      - ./frontend/static:/app/static
      - ./frontend/assets:/app/assets
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --url http://nginx:80
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    deploy:
      replicas: ${CLOUDFLARED_REPLICAS}
    volumes:
      - ./certs:/etc/cloudflared/certs
    depends_on:
      - nginx
